### ISSUE TITLE
Strange issue(Auto-Connect on Server Start Fails)

### ISSUE THREAD

**Issue by ygtc** [ntoff/OctoPrint-FanSpeedSlider#12]
When updated to 0.2.0 ,

OctoPrint Automatic Connect on Server Startup feature is fails. I'm using klipper as firmware and noticed that error. Actually it is meaningless but could you check out about this?

Thank you for your work :)

**Comment by ntoff** [comment]
Might be hard since I don't use klipper, I do know there's a missing variable init which is fixed in the master branch but not released yet, could you please try removing the plugin and then install it manually from https://github.com/ntoff/OctoPrint-fanspeedslider/archive/master.zip this? The version number listed in octoprint will stay the same. Give that a try.

If I have to roll something back, were you previously using 0.1.9 or 0.1.8?

**Comment by ntoff** [comment]
You should get an update notification for 0.2.1 which should fix the lack of variable thing, that might also fix the failure to connect on startup. Let me know if it works or not as I don't use klipper so have no real way of testing it unless I dig out a board and try to figure out how to install klipper.

**Comment by ygtc** [comment]
Sorry for late response but this update (0.2.1) is fixed this issue :+1: 

Thank you for fast fix and keep up to good work !! :smile:
