### ISSUE TITLE
Enhancement: Option to execute system command on fan speed changes

### ISSUE THREAD

**Issue by b-morgan** [ntoff/OctoPrint-FanSpeedSlider#8]
I've installed some external fans on my printer controlled by a hat connected to my Raspberry Pi. I want the speed of those fans to mirror the speed set by the GCode commands M106 Sn (and M107).

Since this plugin "intercepts" the M106 commands, it is the perfect place to add executing a system command passing the S value as a parameter. I have modified your code to do just that and have attached it along with the scripts that I call with it (I'm not sure if the error handling is adequate so I'd accept any suggestions).

If you are interested in including my enhancement, then I would generalize the concept and add two settings,  the command to execute on M106 and the command to execute on M107. The defaults would be nothing (empty string) and the plugin would work exactly as it does now. 

If you are not interested, I'll stumble on by myself.

I'm still learning how to develop a plugin (and using git) so it would take me a while to get the additional UI working. Your help would be greatly appreciated! 

[fanspeedslider.zip](https://github.com/ntoff/OctoPrint-FanSpeedSlider/files/1944698/fanspeedslider.zip)

**Comment by b-morgan** [comment]
I think this is the proper implementation of my enhancement request. You should check to see if I got the UI bits right (and it also fixes [Issue #9 ](https://github.com/ntoff/OctoPrint-FanSpeedSlider/issues/9))

[fanspeedslider2.zip](https://github.com/ntoff/OctoPrint-FanSpeedSlider/files/1945300/fanspeedslider2.zip)

**Comment by ntoff** [comment]
Unfortunately I don't have any of the hardware to test this myself to see if the error handling is adequate and I myself don't know enough to say either way without actually trying it (since I can't execute any of the commands I'm assuming no matter what, I'll always get some sort of error). I'm also not entirely sure this plugin is really that well suited to this purpose. I think a standalone "Fan GPIO Mirror" plugin would be better, where all it does is mirror the fan speed to the pi's GPIO pin. 

The reason I don't really think it's suitable is because external fan hubs are available and can easily extend a single parts cooling fan's output to 2 or 3 or more fans, and often you can simply attach multiple fans to the same parts fan header on the printer's control board (after all, the fan output is typically the same kind of output that drives the heaters, so it's capable of driving *many* standard fans). Attaching them to the Pi feels like it's overly complicating things (unlike something like, for example, an RGB LED strip that indicates the fan speed, that might need some sort of serial data to function and is definitely far beyond me). 

As for the commands / settings / UI, if you were to create a standalone plugin that only does the mirroring, I don't see why you'd need any settings at all. Just have it hard wired to call "fan_on.py" and "fan_off.py", but I wouldn't rely on M107 either because some slicers will actually use M106 S0 to turn the fan off, and M106 Snnn to turn it on (where nnn is a number).

My starting point for the plugin was the example in the octoprint docs http://docs.octoprint.org/en/master/plugins/hooks.html?highlight=rewrite#id10 and doesn't need to be nearly as complicated as what I have if you aren't doing any sort of checking for values outside of a set range. You don't even need to re-write any values if you're just mirroring it, all you'd need to do is intercept any M106 value.

**Comment by b-morgan** [comment]
OK. 
The reason I went this route is that on my LulzBot TAZ 6, the cooling fans are 24V. 24v fans are harder to obtain (and are more expensive) than 12V fans. 

I thought about adding two fans at a time in series and attaching them to the printer's control board but the printer is still under warranty and I'm sure that modification would be frowned upon if I had to make a claim.

Using the Raspberry Pi to control the fans was less expensive and less risky than damaging my printer.

As for testing, the example commands I attached talk to the hat on the Raspberry Pi, but "/home/pi/fan.sh":
```
#!/bin/bash
echo $1 $2 $3 >>/home/pi/fan.txt
exit 0
```
will work just as well. As for M107 being deprecated, M106 S0 works correctly.

In any case, I'll keep what I've done locally and see about creating my own plugin.

**Comment by ntoff** [comment]
You might want to look at the gcode sent event http://docs.octoprint.org/en/master/plugins/hooks.html?highlight=rewrite#octoprint-comm-protocol-gcode-phase rather than the queuing event I'm using. You could look for the M106 Snnn sent event, copy the number, and then send it on to the Pi's GPIO script. 

If you were to write your own plugin, I'd say it'll be quite popular as I've seen a few people ask about controlling a 12v fan on a 24v printer. 

Just be aware that if someone is printing from an SD card, OctoPrint won't see that gcode and so won't be able to respond to it. I know it sounds weird to run octoprint but print from SD card but some people do, they start a print using octoprint just for the timelapse functionality and print off the printer's built in sd card (if it has one).

If you need live help you can try the IRC channel listed on https://discourse.octoprint.org/t/welcome-to-this-forum/8 (I see you've already found the forum).

**Comment by ntoff** [comment]
I'm struggling with whether or not to close this issue.

On the one hand I don't think a fan speed plugin should be able to execute "random" system commands or shell scripts (the literal title of the request), but at the same time I absolutely would love to put in a feature to mirror the pwm signal to a raspberry pi GPIO pin (the spirit of the request) **IF** *I can figure out how to do that, and make it so the plugin still runs on non-raspberry pi hardware* (since I myself am running OctoPrint on a PCDuino).

I'll leave this open for now and think about it, and see if I can work out a way to even test this should I attempt to implement it (lack of raspberry pi hats & such so I can't directly control any type of motor).

**Comment by b-morgan** [comment]
The solution I proposed and have implemented adds to this plugin the ability to execute a system command (or shell script) passing the S parameter to the command. I thought this was a more general solution and allows for the separation of the implementation on the Raspberry Pi of the GPIO or hat code from OctoPrint.

It therefore doesn't matter what host is running OctoPrint and it doesn't matter what the hardware implementation is. You aren't even limited to using Python for your hardware implementation. In fact, you could write code or scripts on the host to interface with another piece of hardware and that hardware could even be located elsewhere on the network.

As for testing, I provided scripts that when executed by this plugin, just write the parameter value to a log file.

My enhanced FanSpeedSlider is working very well. I've used the scripts standalone to help cool the extruder so I can switch between single and dual and I don't have to worry about forgetting to turn the fans off for the next print because the initial M107 (or M106 S0) does that for me.

If you want to reconsider, I can do a pull and a push request or you can do it with the files I have provided here.

**Comment by ntoff** [comment]
Closing this issue since I've created this plugin: https://github.com/ntoff/OctoPrint-Gpiofan which should mirror fan pwm values to a GPIO pin (hopefully).
